### ISSUE TITLE
Add use of terraform provider default tags

### ISSUE THREAD

**Issue by doc-E-brown** [harrison-ai/cookiecutter-terraform#5]
### Description

Terraform now provides the ability for a standard set of default tags to be defined at the provider level [https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider](https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider).  This will have the benefit of significantly less code repetition as well as guaranteeing tags are placed on resources.  This will ensure we do not miss tags on particular resources and that costs can be tracked effectively.

**Note:** the Name of each resource will still need to be provided as an individual tag to the individual resource.

### What changes are being proposed?
1. Update the cookiecutter to add the corresponding default tags to each provider.tf file.  Only `Name` and other resource specific tags will need to be added to the repo.
2. All tag names be Title case to be consistent with Name.  See the example below

### Example provider.tf file as per [default-tags](https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider)

```HCL
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region  = local.region
  profile = local.profile

  default_tags {
    tags = {
      Environment = local.env_name
      Project     = local.project
      Repo        = "new-repo-name"
    }
  }
}

```

**Comment by schattingh** [comment]
Addressed in https://github.com/harrison-ai/cookiecutter-terraform/pull/9
